// <auto-generated />
using System;
using Conestoga_Virtual_Game_Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConestogaVirtualGameStore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20190920201431_mig5")]
    partial class mig5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Command", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<int?>("Orderid");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("Orderid");

                    b.ToTable("Command");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.CreditCard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Memberid");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Familyship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Memberid");

                    b.Property<int?>("Memberid1");

                    b.HasKey("id");

                    b.HasIndex("Memberid");

                    b.HasIndex("Memberid1");

                    b.ToTable("Familyship");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Friendship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Memberid");

                    b.Property<int?>("Memberid1");

                    b.HasKey("id");

                    b.HasIndex("Memberid");

                    b.HasIndex("Memberid1");

                    b.ToTable("Friendship");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Member", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("members");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Memberid");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Ownership", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("Memberid");

                    b.ToTable("Ownership");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("Memberid");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Registration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Memberid");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("Memberid");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Wish", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("Memberid");

                    b.ToTable("Wish");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Command", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("commands")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Order")
                        .WithMany("commands")
                        .HasForeignKey("Orderid");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.CreditCard", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("creditCards")
                        .HasForeignKey("Memberid");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Familyship", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("relatives0")
                        .HasForeignKey("Memberid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("relatives1")
                        .HasForeignKey("Memberid1");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Friendship", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("friends0")
                        .HasForeignKey("Memberid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("friends1")
                        .HasForeignKey("Memberid1");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Order", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("orders")
                        .HasForeignKey("Memberid");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Ownership", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("members")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("games")
                        .HasForeignKey("Memberid");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Rating", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("ratings")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("ratings")
                        .HasForeignKey("Memberid");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Registration", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("registrations")
                        .HasForeignKey("Memberid");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Review", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("reviews")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("reviews")
                        .HasForeignKey("Memberid");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Wish", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("wishes")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("wishes")
                        .HasForeignKey("Memberid");
                });
#pragma warning restore 612, 618
        }
    }
}
