// <auto-generated />
using System;
using Conestoga_Virtual_Game_Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConestogaVirtualGameStore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20191003203121_Updated userRole")]
    partial class UpdateduserRole
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Command", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<int?>("Orderid");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("Orderid");

                    b.ToTable("Command");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.CreditCard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Familyship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId");

                    b.Property<string>("UserId1");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Familyship");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Friendship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId");

                    b.Property<string>("UserId1");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId1");

                    b.ToTable("Friendship");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UserId");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Ownership", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<string>("UserId");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("UserId");

                    b.ToTable("Ownership");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Rating", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<string>("UserId");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("UserId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Registration", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Eventid");

                    b.Property<string>("UserId");

                    b.HasKey("id");

                    b.HasIndex("Eventid");

                    b.HasIndex("UserId");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Review", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<string>("UserId");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("UserId");

                    b.ToTable("Review");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Wish", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<string>("UserId");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("UserId");

                    b.ToTable("Wish");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUserRole<string>");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.User", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");


                    b.ToTable("User");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.Property<string>("UserId1");

                    b.HasIndex("UserId1");

                    b.ToTable("UserRole");

                    b.HasDiscriminator().HasValue("UserRole");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Command", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("commands")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Order")
                        .WithMany("commands")
                        .HasForeignKey("Orderid");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.CreditCard", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("creditCards")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Familyship", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("relatives0")
                        .HasForeignKey("UserId");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("relatives1")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Friendship", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("friends0")
                        .HasForeignKey("UserId");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("friends1")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Order", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("orders")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Ownership", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("owners")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("games")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Rating", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("ratings")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("ratings")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Registration", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Event")
                        .WithMany("registrations")
                        .HasForeignKey("Eventid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("registrations")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Review", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("reviews")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("reviews")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Wish", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("wishes")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("wishes")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.UserRole", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId1");
                });
#pragma warning restore 612, 618
        }
    }
}
