// <auto-generated />
using System;
using Conestoga_Virtual_Game_Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConestogaVirtualGameStore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20190920190920_mig4")]
    partial class mig4
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.CreditCard", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Memberid");

                    b.ToTable("CreditCard");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Familyship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Memberid");

                    b.Property<int?>("Memberid1");

                    b.HasKey("Id");

                    b.HasIndex("Memberid");

                    b.HasIndex("Memberid1");

                    b.ToTable("Familyship");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Friendship", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Memberid");

                    b.Property<int?>("Memberid1");

                    b.HasKey("id");

                    b.HasIndex("Memberid");

                    b.HasIndex("Memberid1");

                    b.ToTable("Friendship");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.GameOwnership", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("Memberid");

                    b.ToTable("GameOwnership");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Member", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address");

                    b.Property<string>("city");

                    b.Property<string>("firstname");

                    b.Property<string>("lastname");

                    b.Property<string>("postal_code");

                    b.HasKey("id");

                    b.ToTable("members");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.CreditCard", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("creditCards")
                        .HasForeignKey("Memberid");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Familyship", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("relatives0")
                        .HasForeignKey("Memberid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("relatives1")
                        .HasForeignKey("Memberid1");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Friendship", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("friends0")
                        .HasForeignKey("Memberid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("friends1")
                        .HasForeignKey("Memberid1");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.GameOwnership", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("members")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("games")
                        .HasForeignKey("Memberid");
                });
#pragma warning restore 612, 618
        }
    }
}
