// <auto-generated />
using System;
using Conestoga_Virtual_Game_Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConestogaVirtualGameStore.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20190919202009_Init2")]
    partial class Init2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Game", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("games");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.GameOwnership", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Gameid");

                    b.Property<int?>("Memberid");

                    b.HasKey("id");

                    b.HasIndex("Gameid");

                    b.HasIndex("Memberid");

                    b.ToTable("GameOwnership");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.Member", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("id");

                    b.ToTable("members");
                });

            modelBuilder.Entity("Conestoga_Virtual_Game_Store.Models.GameOwnership", b =>
                {
                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Game")
                        .WithMany("members")
                        .HasForeignKey("Gameid");

                    b.HasOne("Conestoga_Virtual_Game_Store.Models.Member")
                        .WithMany("games")
                        .HasForeignKey("Memberid");
                });
#pragma warning restore 612, 618
        }
    }
}
